#:schema node_modules/wrangler/config-schema.json
name = "english-tutoring-api"
type = "javascript"
compatibility_date = "2023-10-05"

account_id = "89c48b3cdc75b8848ea717109decd49f"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "english-tutoring-p1"
database_id = "a30faccc-6ee4-4922-a06d-57358d9a1d76"
